autocmd BufWritePost .vimrc source %
set encoding=utf-8
set laststatus=2
set t_Co=256

call plug#begin('~/.vim/plugged')

Plug 'easymotion/vim-easymotion'
Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }
Plug 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plug 'junegunn/fzf.vim'
Plug 'tmhedberg/SimpylFold'
Plug 'tpope/vim-surround'
Plug 'vim-scripts/indentpython.vim'
Plug 'Valloric/YouCompleteMe', {'do':'./install.py --all'}
Plug 'nvie/vim-flake8'
Plug 'scrooloose/nerdtree'
Plug 'jistr/vim-nerdtree-tabs'
Plug 'tpope/vim-fugitive'
Plug 'vim-airline/vim-airline'
Plug 'tpope/vim-commentary'
Plug 'christoomey/vim-system-copy'
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'
Plug 'rstacruz/sparkup'
Plug 'jiangmiao/auto-pairs'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'tmhedberg/matchit'
Plug 'mileszs/ack.vim'
Plug 'christoomey/vim-tmux-navigator'
Plug 'epilande/vim-es2015-snippets'
Plug 'mattn/emmet-vim'
let g:user_emmet_leader_key='<C-Z>'
Plug 'epilande/vim-react-snippets'
Plug 'arzg/vim-colors-xcode'
let g:UltiSnipsExpandTrigger="<C-l>""
call plug#end()

source ~/.vim/startup/settings.vim
source ~/.vim/startup/mappings.vim
source ~/.vim/startup/compileAndRun.vim
source ~/.vim/startup/pluginsSettings.vim

let NERDTreeIgnore=['\.pyc$', '\~$'] "ignore files in NERDTree

let g:jsx_ext_required = 0 " Allow JSX in normal JS files"
